### ISSUE TITLE
"yarn ios" Error: Element type is invalid: expected a string. Check the render method of `SettingsScreen`.

### ISSUE THREAD

**Issue by ywongweb** [wix-incubator/react-native-wix-engine-playground#1]
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `SettingsScreen`.

This error is located at:
    in RCTView (at SettingsScreen.js:18)
    in SettingsScreen (at ComponentWrapper.js:37)
    in WrappedComponent (at renderApplication.js:45)
    in RCTView (at AppContainer.js:109)
    in RCTView (at AppContainer.js:135)
    in AppContainer (at renderApplication.js:39)
```

![image](https://user-images.githubusercontent.com/1422851/103688340-98f15a00-4f89-11eb-8df7-f71f5e5f8935.png)

### Steps to replicate:
1. clone repo
2. cd `app-example` 
3. `yarn && yarn ios`
errors

Also tried doing `yarn` inside both module folders then re-run, same error.

**Comment by ywongweb** [comment]
This is because the `setting module` on NPM is missing [this line](https://github.com/wix-incubator/react-native-wix-engine-playground/blob/main/module-settings/src/SettingsScreen.js#L16)

As a workaround to get the app running locally, we can temporarily change [this line](https://github.com/wix-incubator/react-native-wix-engine-playground/blob/main/app-example/package.json#L21)
![image](https://user-images.githubusercontent.com/1422851/104245598-731df680-545c-11eb-92a6-11f8c1161459.png)
to 
`"wix-engine-playground-module-settings": "file:../module-settings"`

Then do a `yarn` after.

**Comment by bruchim** [comment]
Hey,
My bad, I forgot to publish `wix-engine-playground-module-blog` after the change.

Fixed, and it should work now.
