### ISSUE TITLE
Why does module-blog contain native deps in package.json?

### ISSUE THREAD

**Issue by ajzozakiewicz** [wix-incubator/react-native-wix-engine-playground#2]
Hello @bruchim,

I am trying to understand the package structure between modules and the engine. It was my understanding that modules should not install any native deps, but rather get those deps from the engine itself. Can you explain why module-blog has native deps installed? How are js deps handled in each module?

That seems to be one thing that is not explained in detail in the deep dive for module repos. (https://medium.com/wix-engineering/react-native-at-wix-the-architecture-ii-deep-dive-9cfcb3c2822c)

Thanks in advance! This architecture is super interesting. Hoping to implement a similar solution.

AJ

**Comment by ajzozakiewicz** [comment]
Thinking about this more. JS deps are not an issue as these modules get installed as node modules and it would work the same as any node module does. But the question on native deps still stands.. Thanks!

**Comment by bruchim** [comment]
hey @ajzozakiewicz, 
You are right, all of these dependencies are there by mistake, probably bad copy-paste 👍 
Modules should not include any native dependencies, but only JS libraries 

I fixed that, and now the only one left there is `remx` (all the rest are used by the engine already) :
https://github.com/wix-incubator/react-native-wix-engine-playground/blob/main/module-blog/package.json#L21

**Comment by ajzozakiewicz** [comment]
Okay, that makes total sense. Thanks for the quick response!
