### ISSUE TITLE
Module resolution for local dev

### ISSUE THREAD

**Issue by ajzozakiewicz** [wix-incubator/react-native-wix-engine-playground#3]
Hey @bruchim,

One point I am stuck on within the build process is how module resolution occurs from a module repo. I do not see any hard coded paths to the local source files. Is there some magic with watchman or the metro bundler that is resolving `require('wix-engine-playground-module-blog').default` in `engine_autogenerated/modules.js`?

From what I can tell you are manually spinning up the react-native packager and pointing it to the local folder for module-blog. That would cover watching and rebuilding the module source files correct?

From there I am just confused as to how the engine is resolving the modules.js require.

Any info you could provide on this would be much appreciated.

Thanks!

**Comment by bruchim** [comment]
Hey @ajzozakiewicz,

The resolving is done by the name of the module in the "name" section in your `package.json` and the "main" section which should point to the `module.js` file.
``` js
  "main": "./src/module.js",
  "name": "wix-engine-playground-module-blog",
```

I hope it answers your question.

**Comment by ajzozakiewicz** [comment]
Sure, when `wix-engine-playground-module-blog` is installed as an NPM module it will resolved that way. Will the metro bundler know to resolve it though for local dev? When I say local dev, I am in the `module-blog` repo, running `rn-wix-engine -p engineConfig.json -i`. `engineConfig.json` contains a ref to `"wix-engine-playground-module-blog"`.

When running within `module-blog` how does the metro bundler know to resolve this to the local folder rather than "wix-engine-playground-module-blog" from node_modules?

So I am looking at this config:
https://github.com/wix-incubator/react-native-wix-engine-playground/blob/main/module-blog/engineConfig.json

And running `npm run ios` here:
https://github.com/wix-incubator/react-native-wix-engine-playground/blob/main/module-blog/package.json

Hope this clarifies my question. Kind of hard to explain. Appreciate the help.

**Comment by ajzozakiewicz** [comment]
Using a babel transform I am sure you could resolve any refs to the local project folder, but I didnt see any special transforms for this to work.

**Comment by bruchim** [comment]
One of the search paths of metro is the current module, so `wix-engine-playground-module-blog` not have to be in your `node_module` folder but in one of the following:

```
myProject/
myProject/node_modules/
myProject/node_modules/@scope/
/usr/local/lib/node_modules/
/usr/local/lib/node_modules/@scope
/usr/local/lib/node_modules/npm/node_modules/
/usr/local/lib/node_modules/npm/node_modules/@scope
$HOME/.npm/
$HOME/.npm/@scope/
```

If you interested you can dig into metro ModuleResolution logic here:
https://github.com/facebook/metro/blob/master/packages/metro/src/node-haste/DependencyGraph/ModuleResolution.js

**Comment by ajzozakiewicz** [comment]
Awesome, that makes perfect sense now. Guess I need to get in a better habit of reading source code...

Thanks for pointing me in the right direction on this one.
